src/pages/_document.tsx, src/ui/Typography/Typography.css.ts, src/ui/Typography/Typography.test.tsx, src/ui/Typography/Typography.tsx, src/ui/Typography/__snapshots__/Typography.test.tsx.snap, src/ui/Typography/index.ts, src/ui/index.ts, src/ui/reset.css.ts
=> feat: typography component

package.json, src/ui/Box/Box.tsx, src/ui/Box/__snapshots__/Box.test.tsx.snap, src/ui/Typography/Typography.css.ts, src/ui/Typography/Typography.tsx, src/ui/Typography/__snapshots__/Typography.test.tsx.snap, src/ui/sprinkles.css.ts, src/ui/tokens/color.ts, src/ui/utils.ts, yarn.lock
- change className handling in Box component
- change Typography variables using recipes
- add semi bold font-weight
- fix misspelled sprinkles file name
=> refactor: refactor UI components

package.json, src/context/auth/authContext.tsx, src/context/auth/index.ts, src/context/auth/useAuth.tsx, src/lib/supabase.ts, src/pages/_app.tsx, src/pages/index.tsx, yarn.lock
- supabase goole login 구현
- context를 통한 유저정도와 session 정보에 접근 가능하도록 구현
=> supabase google login

.eslintrc.js, jest.config.js, package.json, pnpm-lock.yaml, src/components/AsyncBoundary/AsyncBoundary.test.tsx, src/components/AsyncBoundary/SSRSuspense.tsx, src/components/AsyncBoundary/index.tsx, src/components/AsyncBoundary/interfaces.ts, src/hooks/index.ts, src/hooks/useInit.ts, src/hooks/useMounted.ts, src/pages/_app.tsx, src/pages/index.tsx, src/queries/getMeQuery.ts, src/queries/index.ts, src/queryClient.ts, src/types/ServerResponseBase.ts, src/types/index.ts, src/utils/getCookie.ts, src/utils/getServerSidePropsWithCookies.ts, src/utils/index.ts, src/utils/kyInstance.ts, src/utils/localStorage/helper.ts, src/utils/localStorage/index.ts, src/utils/testUtils/customRender.tsx, src/utils/testUtils/hideErrorLog.ts, src/utils/testUtils/index.ts
- AsyncBoundary 컴포넌트 구현
- refresh token 기능 구현
- 구글 로그인 기능 구현 (카카오 로그인 추가 작업 필요)
- server-side cookie 핸들링 로직 구현
=> feat: login 기능 개발

package.json, pnpm-lock.yaml, src/pages/index.tsx, src/ui/Box/Box.test.tsx, src/ui/Box/__snapshots__/Box.test.tsx.snap, src/ui/Toggle/Toggle.css.ts, src/ui/Toggle/Toggle.test.tsx, src/ui/Toggle/Toggle.tsx, src/ui/Toggle/__snapshots__/Toggle.test.tsx.snap, src/ui/Toggle/index.ts, src/ui/Typography/Typography.test.tsx, src/ui/Typography/__snapshots__/Typography.test.tsx.snap, src/ui/index.ts, src/ui/sprinkles.css.ts, src/ui/tokens/color.ts, src/ui/tokens/index.ts, src/ui/tokens/layout.ts, src/ui/tokens/size.ts, src/ui/tokens/space.ts, src/ui/tokens/theme.css.ts
- add Toggle Component (resolve #67)
- update theme token
- refactor token added to global css variables
=> feat: Toggle Component

src/hooks/index.ts, src/hooks/useToggle.ts, src/types/Component.ts, src/types/index.ts, src/ui/Box/Box.tsx, src/ui/Button/Button.css.ts, src/ui/Button/Button.tsx, src/ui/Button/Button.type.ts, src/ui/Form/FormField.test.tsx, src/ui/Form/FormField.tsx, src/ui/Form/index.ts, src/ui/Icon/Icon.tsx, src/ui/Input/Input.css.ts, src/ui/Input/Input.test.tsx, src/ui/Input/Input.tsx, src/ui/Input/Input.type.ts, src/ui/Input/index.ts, src/ui/Typography/Typography.tsx, src/ui/fontBase.css.ts, src/ui/index.ts
인풋 컴포넌트 개발
- 인풋 컴포넌트 개발
- FormField 컴포넌트 개발
- fontCss 분리
- css 변수 컨벤션 통일
- 버튼 컴포넌트 Icon 컬러 버그 수정
- resolve #66
=> feat: input

.github/workflows/storybook.yaml
=> fix: storybook deploy action

.github/workflows/storybook.yaml
storybook action수정
- storybook action수정
=> fix: storybook action

.github/workflows/storybook.yaml, src/ui/Box/Box.stories.tsx
`Box` 스토리북 작성
- `Box` 스토리북 작성
- x
=> chore: `Box` 스토리북 작성

src/hooks/index.ts, src/hooks/useInit.ts, src/hooks/useIsomorphicLayoutEffect.ts, src/hooks/useWindowSize.ts, src/pages/_app.tsx, src/ui/global.css.ts
웹뷰 관련 css 추가
- viewport meta 태그
- useWindowSize hook
- body 높이 고정
- X
=> chore: webview css properties

src/pages/chat.tsx, src/pages/index.tsx, src/pages/search.tsx, src/pages/user.tsx, src/ui/Layout/BottomTab/BottomTab.css.ts, src/ui/Layout/BottomTab/BottomTab.tsx, src/ui/Layout/BottomTab/BottomTabItem.tsx, src/ui/Layout/BottomTab/index.ts, src/ui/Layout/index.ts, src/ui/global.css.ts, src/ui/index.ts
`BottomTab`컴포넌트 구현
- `BottomTab`컴포넌트 구현
- BNF-2 #done
=> feat: `BottomTab` 구현

src/pages/index.tsx, src/ui/Layout/Header/Back.tsx, src/ui/Layout/Header/Header.css.ts, src/ui/Layout/Header/Header.tsx, src/ui/Layout/Header/Notification.tsx, src/ui/Layout/Header/index.ts, src/ui/Layout/Layout.tsx, src/ui/Layout/index.ts, src/ui/global.css.ts
헤더 컴포넌트 개발
- 헤더 컴포넌트 개발
- Layout 컴포넌트 개발
- BNF-11 #done
=> feat: 헤더 컴포넌트 개발

.github/workflows/ci.yaml, .github/workflows/lighthouse-ci.yaml, .gitignore, lighthouserc.js, package.json
=> chore: add lighthouse ci

src/hooks/useDebouncedCallback/index.ts, src/hooks/useDebouncedCallback/useDebouncedCallback.test.ts
`useDebouncedCallback` 훅 개발
- `useDebouncedCallback` 훅 구현
- 테스트 작성
- X
=> feat: useDebouncedCallback

package.json, pnpm-lock.yaml, src/components/LazyDomMaxMotion.tsx, src/modules/Chat/ChattingList/ChattingRoomsItem.tsx, src/modules/Chat/GuideModal/StepIndicator/index.tsx, src/modules/Chat/GuideModal/index.tsx, src/pages/chat/index.tsx, src/types/ExcludeObject.ts, src/ui/Box/MotionBox.ts, src/ui/PullToClose/PullToClose.tsx
`ChattingRoomsItem` 개선
- feat: `LazyDomMaxMotion` 컴포넌트 구현
- feat: `MotionBox` prop 개선
- feat: `ChattingRoomsItem` animation 추가
- fix: 나가기 텍스트 깨짐
- fix: 간격 및 크기
- feat: 공유안내 모달 적용
- [BNF-13]
[BNF-13]: https://bae-no.atlassian.net/browse/BNF-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: `ChattingRoomsItem` 개선

src/components/IntersectionArea.tsx, src/components/List.tsx, src/graphql/home.graphql, src/graphql/user.graphql, src/modules/Chat/ChattingList/ChattingItem.tsx, src/modules/home/ChattingRooms.tsx, src/modules/home/HomeHead/UserInfo.tsx, src/utils/getDistanceFromCoordinates.ts
=> feat: home 작업 wip

src/pages/login/index.tsx, src/ui/Avatar/Avatar.tsx
access페이지 에러 수정
access페이지 에러 수정
=> acceess 페이지 에러 수정, login 페이지 위치 수정

src/graphql/auth.graphql, src/pages/login/access/[type].tsx
=> 이미 가입한 유저면 홈으로 라우팅

src/pages/login/access/[type].tsx
=> access 페이지 버그 수정

src/modules/home/LocationSelector.tsx
=> fix: fix location selector

src/modules/home/ChattingRooms.tsx
=> fix: home sort

src/components/AsyncBoundary/SSRSuspense.tsx
=> fix: ssr safe suspense fallback

src/ui/Layout/Header/Header.tsx
=> header zindex 수정

src/modules/Chat/ChatWrapper/index.tsx, src/modules/Chat/detailPage/ChatContent/ChatTextArea.tsx
=> textarea 활성화 로직 수정
